// LG Portal Tab - 发布预览
// 内容预览卡 + 内容结构(宏观/中观/微观) + 市场情报 + Pipeline 进度 + 版本历史 + 操作栏

import { useState } from 'react';
import { useOutletContext, useNavigate } from 'react-router-dom';
import type { LGTaskContext } from '../LGTaskDetailLayout';
import { MarkdownRenderer } from '../../components/MarkdownRenderer';

// Pipeline 步骤定义
const PIPELINE_STEPS = [
  { id: 'planning', label: '选题策划', icon: 'lightbulb', desc: '大纲定义完成' },
  { id: 'research', label: '深度研究', icon: 'search', desc: '多源数据采集' },
  { id: 'writing', label: '文稿生成', icon: 'edit_note', desc: 'AI 初稿生成' },
  { id: 'reviews', label: '蓝军评审', icon: 'fact_check', desc: '多轮专家评审' },
  { id: 'approval', label: '最终审批', icon: 'gavel', desc: '人工确认发布' },
  { id: 'publishing', label: '发布就绪', icon: 'publish', desc: '输出最终版本' },
];

// 节点到步骤的映射
const NODE_TO_STEP_INDEX: Record<string, number> = {
  planner: 0,
  human_outline: 0,
  researcher: 1,
  writer: 2,
  blue_team: 3,
  human_approve: 4,
  output: 5,
};

export function LGPortalTab() {
  const { detail, onRefresh } = useOutletContext<LGTaskContext>();
  const navigate = useNavigate();
  const [exporting, setExporting] = useState(false);

  if (!detail) {
    return <div className="tab-panel"><p style={{ color: 'var(--text-muted)' }}>暂无任务数据</p></div>;
  }

  const sections = detail.outline?.sections || [];
  const macroSection = sections[0];
  const mesoSections = sections.slice(1, Math.max(1, sections.length - 1));
  const microSection = sections.length > 2 ? sections[sections.length - 1] : null;

  const draftContent = detail.draftContent || '';
  const wordCount = draftContent.replace(/\s/g, '').length;
  const insights = detail.researchData?.insights || [];
  const dataSourceCount = detail.researchData?.dataPackage?.length || 0;
  const rounds = detail.blueTeamRounds || [];

  const currentStepIdx = NODE_TO_STEP_INDEX[detail.currentNode] ?? -1;

  const getQualityLabel = () => {
    const score = detail.evaluation?.score;
    if (!score) return { label: '--', color: 'var(--text-muted)' };
    if (score >= 80) return { label: '优秀', color: 'var(--success)' };
    if (score >= 60) return { label: '良好', color: 'var(--primary)' };
    return { label: '一般', color: 'var(--warning, #f59e0b)' };
  };

  const quality = getQualityLabel();

  // 导出 Markdown
  const handleExportMarkdown = () => {
    if (!draftContent) return;
    setExporting(true);
    try {
      const blob = new Blob([draftContent], { type: 'text/markdown;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${detail.topic || 'draft'}.md`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  };

  // 导出 HTML
  const handleExportHTML = () => {
    if (!draftContent) return;
    setExporting(true);
    try {
      const html = `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="UTF-8"><title>${detail.topic || 'Report'}</title>
<style>body{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.8;color:#333}
h1,h2,h3{color:#1a1a1a}blockquote{border-left:3px solid #D46648;padding-left:16px;color:#666}</style>
</head><body><h1>${detail.topic || ''}</h1><article>${draftContent}</article>
<footer><p style="color:#999;font-size:12px;margin-top:40px">Generated by LangGraph Content Pipeline</p></footer></body></html>`;
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${detail.topic || 'report'}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="tab-panel" style={{ paddingBottom: '100px' }}>
      {/* Header */}
      <header style={{ marginBottom: '32px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '12px', color: 'var(--text-muted)', marginBottom: '8px' }}>
          <span style={{ fontWeight: 700, textTransform: 'uppercase', color: 'var(--primary)' }}>发布预览</span>
          <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>chevron_right</span>
          <span style={{ fontWeight: 700, textTransform: 'uppercase' }}>预览与发布</span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <h1 style={{ fontSize: '28px', fontWeight: 800, margin: '0 0 8px', color: 'var(--text)' }}>
              {detail.topic || '发布预览'}
            </h1>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', color: 'var(--text-muted)' }}>
              <span style={{ fontFamily: 'monospace', background: 'var(--surface-alt)', padding: '2px 6px', borderRadius: '4px' }}>
                {detail.taskId?.slice(0, 12) || '---'}
              </span>
              <span className={`status-value status-${getStatusClass(detail.status)}`}>
                {getStatusLabel(detail.status)}
              </span>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="lg-btn lg-btn-secondary" onClick={handleExportMarkdown} disabled={!draftContent || exporting}>
              <span className="material-symbols-outlined" style={{ fontSize: '16px', verticalAlign: 'middle', marginRight: '4px' }}>download</span>
              导出 Markdown
            </button>
            <button className="lg-btn lg-btn-primary" onClick={handleExportHTML} disabled={!draftContent || exporting}>
              <span className="material-symbols-outlined" style={{ fontSize: '16px', verticalAlign: 'middle', marginRight: '4px' }}>download</span>
              导出 HTML
            </button>
          </div>
        </div>
      </header>

      {/* Content Preview Card */}
      <div className="info-card full-width" style={{ marginBottom: '24px', overflow: 'hidden' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', minHeight: '200px' }}>
          {/* Draft preview */}
          <div style={{ padding: '24px', borderRight: '1px solid var(--divider)' }}>
            <div style={{ height: '120px', borderRadius: 'var(--radius)', background: 'linear-gradient(135deg, hsla(199,89%,48%,0.15), hsla(270,50%,50%,0.15))', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '16px' }}>
              <span className="material-symbols-outlined" style={{ fontSize: '48px', color: 'var(--primary)', opacity: 0.3 }}>image</span>
            </div>
            <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.7, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
              {draftContent.substring(0, 300) || sections[0]?.content || '内容正在生成中。完成后的内容将在此处显示预览。'}
            </p>
          </div>
          {/* Stats sidebar */}
          <div style={{ padding: '24px', background: 'var(--surface-alt)', display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>字数</div>
              <div style={{ fontSize: '24px', fontWeight: 800, color: 'var(--text)' }}>{wordCount > 0 ? wordCount.toLocaleString() : '--'}</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>内容质量</div>
              <div style={{ fontSize: '24px', fontWeight: 800, color: quality.color }}>{quality.label}</div>
              <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>({detail.evaluation?.score || '--'}/100)</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>核心贡献者</div>
              <div style={{ display: 'flex', gap: '-4px' }}>
                {['AI', 'RE', 'WR', 'BT'].map((role, i) => {
                  const colors = ['#3b82f6', '#22c55e', '#8b5cf6', '#f59e0b'];
                  const bgs = ['#dbeafe', '#dcfce7', '#ede9fe', '#fef3c7'];
                  return (
                    <div key={role} style={{
                      width: '28px', height: '28px', borderRadius: '50%', border: '2px solid var(--surface)',
                      background: bgs[i], display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: '10px', fontWeight: 700, color: colors[i], marginLeft: i > 0 ? '-4px' : 0,
                    }}>{role}</div>
                  );
                })}
              </div>
            </div>
            <button className="lg-btn lg-btn-secondary" style={{ marginTop: 'auto' }} onClick={() => navigate('../writing')}>
              <span className="material-symbols-outlined" style={{ fontSize: '14px', verticalAlign: 'middle', marginRight: '4px' }}>edit</span>
              查看完整草稿
            </button>
          </div>
        </div>
      </div>

      {/* Content Structure + Market Intelligence */}
      <div className="panel-grid" style={{ marginBottom: '24px' }}>
        {/* Content Structure (宏观/中观/微观) */}
        <div className="info-card">
          <div className="card-title">
            <span className="material-symbols-outlined">account_tree</span>
            内容结构
            <span style={{ marginLeft: 'auto', fontSize: '11px', fontWeight: 400, color: 'var(--primary)', cursor: 'pointer' }} onClick={() => navigate('../planning')}>
              查看大纲
            </span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {/* Macro */}
            <div style={{ padding: '10px 12px', background: 'hsla(210, 80%, 60%, 0.08)', borderRadius: 'var(--radius-sm)', border: '1px solid hsla(210, 80%, 60%, 0.15)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                <span style={{ fontSize: '10px', fontWeight: 700, background: 'hsla(210, 80%, 60%, 0.2)', color: '#2563eb', padding: '1px 6px', borderRadius: '3px' }}>宏观</span>
                <span style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text)' }}>{macroSection?.title || '暂无'}</span>
              </div>
              {macroSection?.content && (
                <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>{macroSection.content.substring(0, 80)}</p>
              )}
            </div>
            {/* Meso */}
            {mesoSections.map((section: any, idx: number) => (
              <div key={idx} style={{ marginLeft: '16px', borderLeft: '2px solid var(--divider)', paddingLeft: '12px' }}>
                <div style={{ padding: '8px 10px', background: 'var(--surface-alt)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--divider)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '2px' }}>
                    <span style={{ fontSize: '10px', fontWeight: 700, background: 'var(--surface)', color: 'var(--text-secondary)', padding: '1px 6px', borderRadius: '3px' }}>中观</span>
                    <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text)' }}>{section.title || `中观层级 ${idx + 1}`}</span>
                  </div>
                </div>
              </div>
            ))}
            {/* Micro */}
            {microSection && (
              <div style={{ marginLeft: '32px', borderLeft: '2px solid var(--divider)', opacity: 0.7, paddingLeft: '12px' }}>
                <div style={{ padding: '8px 10px', background: 'var(--surface)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--divider)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span style={{ fontSize: '10px', fontWeight: 700, background: 'var(--surface-alt)', color: 'var(--text-muted)', padding: '1px 6px', borderRadius: '3px' }}>微观</span>
                    <span style={{ fontSize: '12px', fontWeight: 500, fontStyle: 'italic', color: 'var(--text)' }}>{microSection.title}</span>
                  </div>
                </div>
              </div>
            )}
            {sections.length === 0 && (
              <p style={{ color: 'var(--text-muted)', fontSize: '12px', textAlign: 'center', padding: '12px' }}>大纲尚未生成</p>
            )}
          </div>
        </div>

        {/* Market Intelligence */}
        <div className="info-card">
          <div className="card-title">
            <span className="material-symbols-outlined">query_stats</span>
            市场情报洞察
            <span style={{ marginLeft: 'auto', fontSize: '10px', fontWeight: 400, color: 'var(--text-muted)' }}>来源: 深度研究</span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '16px' }}>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase' }}>研究深度</div>
              <div style={{ fontSize: '24px', fontWeight: 800, color: 'var(--success)' }}>{dataSourceCount || '--'}</div>
              <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>个数据来源</div>
            </div>
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase' }}>内容质量</div>
              <div style={{ fontSize: '24px', fontWeight: 800, color: quality.color }}>{quality.label}</div>
              <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>({detail.evaluation?.score || '--'}/100)</div>
            </div>
          </div>
          <div style={{ padding: '12px', background: 'var(--surface-alt)', borderRadius: 'var(--radius)', marginBottom: '12px' }}>
            <div style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text)', marginBottom: '8px' }}>核心研究洞察</div>
            {insights.length > 0 ? (
              <ul style={{ margin: 0, paddingLeft: 0, listStyle: 'none' }}>
                {insights.slice(0, 3).map((insight: any, idx: number) => (
                  <li key={idx} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', marginBottom: '8px' }}>
                    <span className="material-symbols-outlined" style={{ fontSize: '14px', color: 'var(--primary)', marginTop: '2px' }}>auto_awesome</span>
                    <p style={{ fontSize: '11px', color: 'var(--text-secondary)', lineHeight: 1.5, margin: 0 }}>
                      <strong style={{ color: 'var(--text)' }}>[{insight.type}]</strong> {insight.content}
                    </p>
                  </li>
                ))}
              </ul>
            ) : (
              <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>研究尚未完成</p>
            )}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>
              已验证 {dataSourceCount} 个来源
            </span>
            <button className="lg-btn lg-btn-secondary" style={{ fontSize: '11px', padding: '4px 10px' }} onClick={() => navigate('../research')}>
              探索研究数据
            </button>
          </div>
        </div>
      </div>

      {/* Pipeline Progress Timeline */}
      <div className="info-card full-width" style={{ marginBottom: '24px' }}>
        <div className="card-title">
          <span className="material-symbols-outlined">view_timeline</span>
          流水线进度
          <span style={{ marginLeft: 'auto', fontSize: '11px', fontWeight: 400, color: 'var(--text-muted)' }}>
            当前: {getStatusLabel(detail.status)}
          </span>
        </div>
        <div style={{ position: 'relative', padding: '8px 0 8px 16px' }}>
          {/* Vertical progress line */}
          <div style={{
            position: 'absolute', left: '30px', top: '16px', bottom: '16px', width: '2px',
            background: `linear-gradient(to bottom, var(--primary) ${Math.max(0, ((currentStepIdx + 1) / PIPELINE_STEPS.length) * 100)}%, var(--divider) ${Math.max(0, ((currentStepIdx + 1) / PIPELINE_STEPS.length) * 100)}%)`,
          }} />
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {PIPELINE_STEPS.map((step, i) => {
              const isDone = i <= currentStepIdx;
              const isCurrent = i === currentStepIdx;
              return (
                <div key={step.id} style={{ display: 'flex', gap: '16px', alignItems: 'flex-start', position: 'relative' }}>
                  <div style={{
                    width: '32px', height: '32px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    flexShrink: 0, zIndex: 1,
                    background: isDone ? 'var(--primary)' : isCurrent ? 'var(--primary-alpha)' : 'var(--surface-alt)',
                    color: isDone ? '#fff' : isCurrent ? 'var(--primary)' : 'var(--text-muted)',
                    border: isCurrent ? '2px solid var(--primary)' : 'none',
                    boxShadow: isCurrent ? '0 0 0 4px var(--primary-alpha)' : 'none',
                  }}>
                    <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>
                      {isDone && !isCurrent ? 'check' : step.icon}
                    </span>
                  </div>
                  <div>
                    <div style={{ fontSize: '13px', fontWeight: isDone || isCurrent ? 700 : 400, color: isDone || isCurrent ? 'var(--text)' : 'var(--text-muted)' }}>
                      {step.label}
                    </div>
                    <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                      {step.id === 'research' && dataSourceCount > 0 ? `${step.desc} (${dataSourceCount} 个来源)` :
                       step.id === 'reviews' && rounds.length > 0 ? `${rounds.length} 轮评审完成` :
                       step.desc}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Version History (from blueTeamRounds) */}
      {rounds.length > 0 && (
        <div className="info-card full-width" style={{ marginBottom: '24px' }}>
          <div className="card-title">
            <span className="material-symbols-outlined">history</span>
            修订历史
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {/* Final version */}
            <div style={{ padding: '10px 12px', borderRadius: 'var(--radius-sm)', background: 'var(--surface-alt)', border: '1px solid var(--divider)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '2px' }}>
                <span style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text)' }}>最终版本 (当前)</span>
                <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>经 {rounds.length} 轮修订</span>
              </div>
              <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>
                {detail.reviewPassed ? '评审通过，待最终审批' : '修订中'}
              </p>
            </div>
            {/* Revision rounds */}
            {rounds.slice().reverse().map((round: any, idx: number) => (
              <div key={idx} style={{ padding: '10px 12px', borderRadius: 'var(--radius-sm)', border: '1px solid transparent' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '2px' }}>
                  <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text)' }}>第 {round.round} 轮修订</span>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>{round.questions?.length || 0} 条评审意见</span>
                </div>
                <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>
                  {round.revisionSummary || '版本更新'}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Bottom Action Bar */}
      <div style={{
        position: 'fixed', bottom: 0, left: '256px', right: 0, height: '72px',
        background: 'var(--surface)', backdropFilter: 'blur(12px)',
        borderTop: '1px solid var(--divider)', zIndex: 40,
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 32px',
        boxShadow: '0 -4px 20px -10px rgba(0,0,0,0.1)',
      }}>
        <div style={{ maxWidth: '1000px', width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{
              width: '8px', height: '8px', borderRadius: '50%',
              background: detail.status === 'completed' ? 'var(--success)' : 'var(--primary)',
              animation: detail.status === 'completed' ? 'none' : 'pulse 1.5s infinite',
            }} />
            <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              {detail.status === 'completed' ? '已准备就绪，可导出发布' : '流水线处理中...'}
            </span>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="lg-btn lg-btn-secondary" onClick={onRefresh}>
              <span className="material-symbols-outlined" style={{ fontSize: '16px', verticalAlign: 'middle', marginRight: '4px' }}>replay</span>
              刷新状态
            </button>
            <button
              className="lg-btn lg-btn-primary"
              onClick={handleExportHTML}
              disabled={detail.status !== 'completed' || !draftContent}
              style={{ opacity: detail.status === 'completed' && draftContent ? 1 : 0.5 }}
            >
              <span className="material-symbols-outlined" style={{ fontSize: '16px', verticalAlign: 'middle', marginRight: '4px' }}>publish</span>
              发布最终版本
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function getStatusClass(status: string): string {
  if (status.includes('pending') || status === 'created') return 'pending';
  if (status.includes('planning') || status.includes('outline')) return 'planning';
  if (status.includes('research')) return 'researching';
  if (status.includes('writing') || status.includes('revision')) return 'writing';
  if (status.includes('review') || status.includes('approv')) return 'reviewing';
  if (status === 'completed') return 'completed';
  return 'pending';
}

function getStatusLabel(status: string): string {
  const map: Record<string, string> = {
    created: '已创建', outline_pending: '待确认大纲', outline_confirmed: '大纲已确认',
    researching: '研究中', researching_complete: '研究完成', writing: '写作中',
    writing_complete: '写作完成', reviewing: '评审中', review_passed: '评审通过',
    awaiting_approval: '待最终审批', approved: '已批准', completed: '已完成', failed: '失败',
  };
  return map[status] || status;
}
