// 内容生产流水线 API 参考 — 数据文件 1/3（账号体系 / 生产流水线 / 素材与质量输入）
function G(o){API_GROUPS.push(o);}

G({id:"g-auth",title:"认证与账号",prefix:"/api/auth",desc:"登录、会话、OAuth 与密码管理。支持 Cookie 会话（cp_session）与 X-API-Key 两种凭证。",eps:[
["POST","/api/auth/login","登录（账号+密码），成功返回用户与会话 Cookie"],
["POST","/api/auth/logout","退出登录，注销当前会话"],
["GET","/api/auth/me","获取当前登录用户与默认工作区信息"],
["POST","/api/auth/refresh","刷新会话有效期"],
["POST","/api/auth/switch-workspace","切换当前工作区（多租户）"],
["POST","/api/auth/change-password","修改当前用户密码"],
["GET","/api/auth/oauth/status","查询 OAuth（Google）配置与启用状态"],
["GET","/api/auth/oauth/:provider/start","发起 OAuth 授权跳转"],
["GET","/api/auth/oauth/:provider/callback","OAuth 回调，完成登录"],
]});

G({id:"g-ws",title:"工作区（多租户）",prefix:"/api/workspaces",desc:"Workspace 是数据隔离的第一层边界，用户、资产、任务均挂在工作区下。",eps:[
["GET","/api/workspaces/","列出当前用户可访问的工作区"],
["POST","/api/workspaces/","创建工作区"],
["GET","/api/workspaces/:id","查询工作区详情"],
["PATCH","/api/workspaces/:id","更新工作区信息"],
["DELETE","/api/workspaces/:id","删除工作区"],
["GET","/api/workspaces/:id/members","列出工作区成员"],
["POST","/api/workspaces/:id/members","添加成员"],
["PATCH","/api/workspaces/:id/members/:userId","更新成员角色/权限"],
["DELETE","/api/workspaces/:id/members/:userId","移除成员"],
]});

G({id:"g-admin",title:"管理后台",prefix:"/api/admin",desc:"超管用户管理与管理审计（仅超级管理员可用）。",eps:[
["GET","/api/admin/users/","列出全部用户"],
["POST","/api/admin/users/","创建用户"],
["PATCH","/api/admin/users/:id","更新用户（启用/禁用/角色）"],
["GET","/api/admin/audit/","查询审计日志"],
["GET","/api/admin/audit/stats","审计统计概览"],
["GET","/api/admin/audit/locked-accounts","列出被锁定的账号"],
["POST","/api/admin/audit/unlock","解锁账号"],
]});

G({id:"g-prod",title:"内容生产流水线（核心）",prefix:"/api/v1/production",desc:"产品主线：选题评估 → 研究 → 大纲（可专家评审/对话修订）→ 文稿生成（版本树/差异对比/回滚）→ 蓝军评审（多轮/串行）→ 定稿。68 个端点覆盖任务全生命周期。",eps:[
["POST","/api/v1/production/evaluate-topic","选题价值评估（热点/竞争/可行性打分）"],
["POST","/api/v1/production/","创建生产任务，启动流水线"],
["GET","/api/v1/production/","任务列表（含筛选/分页）"],
["GET","/api/v1/production/:taskId","任务详情与当前阶段状态"],
["PUT","/api/v1/production/:taskId","更新任务基础信息"],
["POST","/api/v1/production/:taskId/approve","审批通过当前阶段，推进流水线"],
["POST","/api/v1/production/:taskId/annotations","添加文稿标注（v4.2 可视化批注）"],
["GET","/api/v1/production/:taskId/annotations","查询文稿标注列表"],
["POST","/api/v1/production/:taskId/outline-chat","大纲对话式修改（自然语言指令）"],
["POST","/api/v1/production/:taskId/outline/expert-review","大纲专家评审（调用专家库）"],
["POST","/api/v1/production/:taskId/outline/confirm","确认大纲，进入写作阶段"],
["GET","/api/v1/production/:taskId/versions","文稿版本列表"],
["GET","/api/v1/production/:taskId/reviews","蓝军评审记录列表"],
["POST","/api/v1/production/:taskId/reviews/:reviewId/accept","接受单条评审意见"],
["GET","/api/v1/production/:taskId/review-items","评审条目列表"],
["POST","/api/v1/production/:taskId/review-items/:reviewId/decide","单条评审决策（采纳/驳回）"],
["POST","/api/v1/production/:taskId/review-items/batch-decide","批量评审决策"],
["GET","/api/v1/production/:taskId/review-summary","评审汇总报告"],
["GET","/api/v1/production/:taskId/can-proceed","查询是否满足进入下一阶段条件"],
["POST","/api/v1/production/:taskId/finalize","定稿发布"],
["GET","/api/v1/production/:taskId/finalize-status","定稿状态查询"],
["POST","/api/v1/production/:taskId/review-items/re-review","申请重新评审"],
["GET","/api/v1/production/:taskId/expert-stats","专家评审参与统计"],
["POST","/api/v1/production/:taskId/save-review-config","保存评审配置（专家组合/轮次）"],
["POST","/api/v1/production/:taskId/apply-revisions","应用修订到文稿"],
["GET","/api/v1/production/:taskId/apply-revisions-status","修订应用进度"],
["GET","/api/v1/production/:taskId/revision-checkpoints","修订检查点列表"],
["GET","/api/v1/production/:taskId/revision-timeline","修订时间线"],
["POST","/api/v1/production/:taskId/redo/planning","重做选题策划阶段"],
["POST","/api/v1/production/:taskId/redo/research","重做深度研究阶段"],
["POST","/api/v1/production/:taskId/redo/writing","重做文稿生成阶段"],
["POST","/api/v1/production/:taskId/redo/review","重做蓝军评审阶段"],
["POST","/api/v1/production/:taskId/redo","重做当前阶段"],
["DELETE","/api/v1/production/:taskId","删除任务（进回收站）"],
["POST","/api/v1/production/:taskId/hide","隐藏任务"],
["POST","/api/v1/production/:taskId/unhide","取消隐藏"],
["GET","/api/v1/production/hidden","已隐藏任务列表"],
["GET","/api/v1/production/:taskId/data-review","数据核查清单（事实/数字审查）"],
["PATCH","/api/v1/production/:taskId/data-review/:itemId","处理单条数据核查项"],
["POST","/api/v1/production/:taskId/data-review/batch","批量处理数据核查项"],
["GET","/api/v1/production/:taskId/data-review/stats","数据核查统计"],
["POST","/api/v1/production/:taskId/cross-validate","数据交叉验证"],
["POST","/api/v1/production/quick-validate","快速事实校验"],
["GET","/api/v1/production/:taskId/final-draft","读取最终文稿"],
["POST","/api/v1/production/:taskId/final-draft/edit","编辑最终文稿"],
["GET","/api/v1/production/:taskId/final-draft/diff","最终文稿差异对比"],
["GET","/api/v1/production/:taskId/final-draft/history","最终文稿修改历史"],
["POST","/api/v1/production/:taskId/outline/comments","添加大纲批注"],
["GET","/api/v1/production/:taskId/outline/comments","大纲批注列表"],
["DELETE","/api/v1/production/:taskId/outline/comments/:commentId","删除大纲批注"],
["GET","/api/v1/production/:taskId/outline/versions","大纲版本列表"],
["GET","/api/v1/production/:taskId/outline/versions/:version","读取指定大纲版本"],
["POST","/api/v1/production/:taskId/outline/compare","大纲版本对比"],
["GET","/api/v1/production/:taskId/draft/progress","文稿生成进度"],
["GET","/api/v1/production/:taskId/draft/generate-stream","文稿生成流式输出（SSE）"],
["GET","/api/v1/production/:taskId/draft/:draftId/revision/progress","文稿修订进度"],
["POST","/api/v1/production/:taskId/draft/:draftId/revision/stream","文稿修订流式输出（SSE）"],
["GET","/api/v1/production/:taskId/revisions","修订列表"],
["GET","/api/v1/production/:taskId/draft/:draftId/diff/:newDraftId","两个文稿版本差异对比"],
["GET","/api/v1/production/:taskId/version-tree","文稿版本树（分支/合并视图）"],
["GET","/api/v1/production/:taskId/draft/:draftId/intermediate-versions","中间版本列表"],
["POST","/api/v1/production/:taskId/draft/:draftId/rollback","回滚到指定文稿版本"],
["GET","/api/v1/production/:taskId/sequential-review/status","串行评审状态"],
["POST","/api/v1/production/:taskId/sequential-review/configure","配置串行评审（顺序/专家链）"],
["POST","/api/v1/production/:taskId/sequential-review/start","启动串行评审"],
["GET","/api/v1/production/:taskId/sequential-review/chain","串行评审链条记录"],
["GET","/api/v1/production/:taskId/sequential-review/versions","串行评审产生的版本"],
["GET","/api/v1/production/:taskId/drafts/:draftId","读取指定文稿草稿"],
]});

G({id:"g-assets",title:"素材资产",prefix:"/api/v1/assets",desc:"素材库：上传、检索、主题分组、来源绑定（目录/平台）与标签管理。",eps:[
["POST","/api/v1/assets/","上传/创建素材"],
["GET","/api/v1/assets/","素材列表"],
["GET","/api/v1/assets/search","素材全文检索"],
["POST","/api/v1/assets/deduplicate","素材去重（sha256/语义相似）"],
["GET","/api/v1/assets/:assetId","素材详情"],
["DELETE","/api/v1/assets/:assetId","删除素材"],
["PATCH","/api/v1/assets/:assetId","更新素材元数据"],
["POST","/api/v1/assets/:assetId/pin","置顶素材"],
["POST","/api/v1/assets/themes","创建主题分组"],
["GET","/api/v1/assets/themes","主题分组列表"],
["GET","/api/v1/assets/themes/:themeId/assets","主题下的素材列表"],
["GET","/api/v1/assets/uncategorized","未分类素材"],
["PATCH","/api/v1/assets/themes/:themeId","更新主题分组"],
["POST","/api/v1/assets/themes/:themeId/pin","置顶主题"],
["DELETE","/api/v1/assets/themes/:themeId","删除主题"],
["GET","/api/v1/assets/bindings","来源绑定列表（目录/平台接入）"],
["POST","/api/v1/assets/bindings","创建来源绑定"],
["GET","/api/v1/assets/bindings/:bindingId","绑定详情"],
["PATCH","/api/v1/assets/bindings/:bindingId","更新绑定"],
["DELETE","/api/v1/assets/bindings/:bindingId","删除绑定"],
["POST","/api/v1/assets/bindings/:bindingId/scan","扫描绑定来源，发现新文件"],
["GET","/api/v1/assets/bindings/:bindingId/files","绑定来源的文件列表"],
["GET","/api/v1/assets/:assetId/usage","素材被引用情况"],
["POST","/api/v1/assets/:assetId/quote","引用素材（生成引用片段）"],
["GET","/api/v1/assets/popular","热门素材"],
["POST","/api/v1/assets/:assetId/auto-tag","AI 自动打标签"],
["PUT","/api/v1/assets/:assetId/tags","手工设置标签"],
]});

G({id:"g-out",title:"产出物",prefix:"/api/v1/outputs",desc:"流水线产出物（成稿）的读取与下载。",eps:[
["GET","/api/v1/outputs/:outputId","读取产出物"],
["GET","/api/v1/outputs/:outputId/download","下载产出物文件"],
]});

G({id:"g-quality",title:"质量输入 · RSS 与资讯条目",prefix:"/api/v1/quality",desc:"v3.x 质量输入体系：RSS 源管理、资讯抓取、条目打分与回收站。",eps:[
["GET","/api/v1/quality/rss-sources","RSS 源列表"],
["POST","/api/v1/quality/rss-sources","新增 RSS 源"],
["PUT","/api/v1/quality/rss-sources/:id","更新 RSS 源"],
["DELETE","/api/v1/quality/rss-sources/:id","删除 RSS 源"],
["POST","/api/v1/quality/rss-sources/crawl","触发 RSS 全量抓取"],
["GET","/api/v1/quality/rss-sources/progress","抓取进度（运行中任务）"],
["GET","/api/v1/quality/rss-sources/history","抓取历史记录"],
["GET","/api/v1/quality/stats","质量体系统计概览"],
["GET","/api/v1/quality/items","资讯条目列表"],
["GET","/api/v1/quality/items/:itemId","条目详情"],
["POST","/api/v1/quality/items/:itemId/import","条目导入素材库"],
["POST","/api/v1/quality/items/:itemId/score","条目质量打分"],
["DELETE","/api/v1/quality/items/:itemId","删除条目（进回收站）"],
["POST","/api/v1/quality/items/batch-delete","批量删除条目"],
["POST","/api/v1/quality/items/:itemId/restore","回收站恢复"],
["GET","/api/v1/quality/items/trash","回收站列表"],
["POST","/api/v1/quality/items/empty-trash","清空回收站"],
["GET","/api/v1/quality/search","资讯全文检索"],
["GET","/api/v1/quality/sources","采集渠道列表"],
["POST","/api/v1/quality/collect","手动触发采集"],
]});

G({id:"g-rec",title:"内容推荐",prefix:"/api/v1/recommendations",desc:"基于热度/质量/受众匹配的选题推荐与反馈闭环。",eps:[
["GET","/api/v1/recommendations/","获取个性化推荐"],
["GET","/api/v1/recommendations/all","全部推荐列表"],
["POST","/api/v1/recommendations/feedback","推荐反馈（喜欢/不相关）"],
["GET","/api/v1/recommendations/stats","推荐效果统计"],
]});

G({id:"g-arch",title:"归档与回收站",prefix:"/api/v1/archive",desc:"任务归档、隐藏与恢复管理。",eps:[
["POST","/api/v1/archive/:taskId/delete","归档删除任务"],
["POST","/api/v1/archive/batch-delete","批量归档删除"],
["POST","/api/v1/archive/:taskId/hide","归档隐藏"],
["POST","/api/v1/archive/:taskId/unhide","取消归档隐藏"],
["POST","/api/v1/archive/batch-hide","批量隐藏"],
["POST","/api/v1/archive/batch-unhide","批量取消隐藏"],
["POST","/api/v1/archive/:taskId/restore","从回收站恢复"],
["POST","/api/v1/archive/:taskId/permanent-delete","永久删除（不可恢复）"],
["GET","/api/v1/archive/recycle-bin","回收站列表"],
["GET","/api/v1/archive/hidden","已归档隐藏列表"],
["POST","/api/v1/archive/cleanup","清理过期归档"],
]});

G({id:"g-res",title:"深度研究",prefix:"/api/v1/research",desc:"研究阶段的配置与资料采集。",eps:[
["GET","/api/v1/research/:taskId/config","读取研究配置"],
["POST","/api/v1/research/:taskId/config","保存研究配置（源/关键词/深度）"],
["POST","/api/v1/research/:taskId/collect","启动资料采集"],
["GET","/api/v1/research/:taskId/preview-search","采集前检索预览"],
["GET","/api/v1/research/:taskId/collected","已采集资料列表"],
]});

G({id:"g-rep",title:"研究报告",prefix:"/api/v1/reports",desc:"研报上传、解析与匹配。",eps:[
["GET","/api/v1/reports/","报告列表"],
["GET","/api/v1/reports/:id","报告详情"],
["POST","/api/v1/reports/upload","上传报告文件"],
["POST","/api/v1/reports/:id/parse","触发报告解析"],
["GET","/api/v1/reports/:id/matches","报告匹配的相关内容"],
["GET","/api/v1/reports/:id/quality","报告质量评估"],
["GET","/api/v1/reports/search","报告检索"],
["DELETE","/api/v1/reports/:id","删除报告"],
]});
