// 数据文件 3/3（v7.x 知识底座：内容库 / 会议纪要 / CEO / 公开API / LLM网关 / LangGraph / AI批处理 / 领域taxonomy）
function G(o){API_GROUPS.push(o);}

G({id:"g-cl",title:"内容库 Content Library (v7.0)",prefix:"/api/v1/content-library",desc:"结构化记忆与层级检索：事实提取（Facts）、实体图谱（Entities）、信念演化（Beliefs）、共识与矛盾检测、跨域关联、维基自动生成，以及 Zep 同步与重新提取任务。",eps:[
["GET","/api/v1/content-library/stats/overview","内容库统计概览"],
["GET","/api/v1/content-library/zep/status","Zep 同步状态"],
["GET","/api/v1/content-library/zep/entities/:name/graph","Zep 实体图谱"],
["GET","/api/v1/content-library/zep/contradictions/:subject","Zep 矛盾检测"],
["GET","/api/v1/content-library/zep/beliefs/:proposition/timeline","Zep 信念演化时间线"],
["GET","/api/v1/content-library/zep/cross-domain/:entity","Zep 跨域关联"],
["POST","/api/v1/content-library/zep/sync/start","启动 Zep 同步任务"],
["GET","/api/v1/content-library/zep/sync/jobs","Zep 同步任务列表"],
["GET","/api/v1/content-library/zep/sync/jobs/:jobId","任务详情"],
["DELETE","/api/v1/content-library/zep/sync/jobs/:jobId","删除任务"],
["GET","/api/v1/content-library/zep/sync/jobs/:jobId/stream","任务进度（SSE）"],
["GET","/api/v1/content-library/dropdown/domains","领域下拉选项"],
["GET","/api/v1/content-library/dropdown/entities","实体下拉选项"],
["GET","/api/v1/content-library/dropdown/beliefs","信念下拉选项"],
["POST","/api/v1/content-library/search","内容库检索（多模态）"],
["GET","/api/v1/content-library/assets/:assetId/tiered","素材分层信息（结构化层级）"],
["POST","/api/v1/content-library/extract","单篇素材事实提取"],
["POST","/api/v1/content-library/reextract","单篇重新提取"],
["POST","/api/v1/content-library/reextract/start","批量重新提取任务"],
["GET","/api/v1/content-library/reextract/jobs","重提取任务列表"],
["GET","/api/v1/content-library/reextract/jobs/:jobId","任务详情"],
["DELETE","/api/v1/content-library/reextract/jobs/:jobId","取消任务"],
["GET","/api/v1/content-library/facts/low-quality","低质量事实清单"],
["POST","/api/v1/content-library/facts/mark-for-reextract","标记事实需重提取"],
["GET","/api/v1/content-library/reextract/preview","重提取效果预览"],
["GET","/api/v1/content-library/reextract/jobs/:jobId/quality","重提取质量评估"],
["GET","/api/v1/content-library/reextract/jobs/:jobId/stream","重提取进度（SSE）"],
["GET","/api/v1/content-library/facts","事实库检索"],
["GET","/api/v1/content-library/entities","实体列表"],
["GET","/api/v1/content-library/topics/recommended","推荐话题"],
["POST","/api/v1/content-library/topics/enrich","话题富化"],
["GET","/api/v1/content-library/gaps","知识空白清单"],
["GET","/api/v1/content-library/trends/:entityId","实体趋势"],
["POST","/api/v1/content-library/search/suggest","检索建议"],
["POST","/api/v1/content-library/search/append","检索追加（增量）"],
["GET","/api/v1/content-library/facts/key","关键事实清单"],
["GET","/api/v1/content-library/entities/:entityId/graph","实体关系图谱"],
["GET","/api/v1/content-library/delta","信息增量报告"],
["GET","/api/v1/content-library/freshness/stale","保鲜度检查（过期事实）"],
["GET","/api/v1/content-library/cards/:entityId","实体卡片（全景视图）"],
["POST","/api/v1/content-library/synthesize","综合生成（多源融合成文）"],
["POST","/api/v1/content-library/synthesize/pregenerate/start","预生成任务启动"],
["GET","/api/v1/content-library/synthesize/pregenerate/jobs","预生成任务列表"],
["GET","/api/v1/content-library/synthesize/pregenerate/jobs/:jobId","任务详情"],
["DELETE","/api/v1/content-library/synthesize/pregenerate/jobs/:jobId","取消任务"],
["GET","/api/v1/content-library/synthesize/pregenerate/jobs/:jobId/stream","预生成进度（SSE）"],
["GET","/api/v1/content-library/synthesize/cache/stats","合成缓存统计"],
["GET","/api/v1/content-library/synthesize/cache","合成缓存内容"],
["GET","/api/v1/content-library/recommendations/:taskType","任务型推荐"],
["GET","/api/v1/content-library/consensus/:topic","话题共识（多源一致结论）"],
["GET","/api/v1/content-library/contradictions","矛盾清单"],
["POST","/api/v1/content-library/contradictions/recall","矛盾召回"],
["GET","/api/v1/content-library/beliefs/:beliefId/timeline","信念演化时间线"],
["GET","/api/v1/content-library/cross-domain/:entityId","跨域关联查询"],
["PUT","/api/v1/content-library/tasks/:taskId/purpose","写入任务意图"],
["GET","/api/v1/content-library/tasks/:taskId/purpose","读取任务意图"],
["POST","/api/v1/content-library/communities/recompute","重算社区结构"],
["POST","/api/v1/content-library/relations/recompute","重算关系图谱"],
["POST","/api/v1/content-library/beliefs/recompute","重算信念演化"],
["POST","/api/v1/content-library/wiki/generate","生成维基条目"],
["GET","/api/v1/content-library/wiki/list","维基条目列表"],
["GET","/api/v1/content-library/wiki/files","维基文件列表"],
["GET","/api/v1/content-library/wiki/preview","维基预览"],
]});

G({id:"g-mn",title:"会议纪要 Meeting Notes",prefix:"/api/v1/meeting-notes",desc:"一库多视图知识库：会议本体（16 轴分析/决策质量/情绪曲线）、人物（承诺/盲点/画像）、范围 Scope（项目/客户/话题）、运行（Runs 分析任务）、跨会议纵向分析、外部接入（上传→解析→分析两段式回调）。",eps:[
["GET","/api/v1/meeting-notes/health","模块健康检查"],
["GET","/api/v1/meeting-notes/","模块总览"],
["GET","/api/v1/meeting-notes/today/stats","今日统计"],
["GET","/api/v1/meeting-notes/meetings","会议列表"],
["POST","/api/v1/meeting-notes/meetings","创建会议记录"],
["POST","/api/v1/meeting-notes/meetings/import-json","JSON 批量导入会议"],
["PUT","/api/v1/meeting-notes/meetings/:id","更新会议"],
["POST","/api/v1/meeting-notes/meetings/:id/archive","归档会议"],
["POST","/api/v1/meeting-notes/meetings/:id/unarchive","取消归档"],
["DELETE","/api/v1/meeting-notes/meetings/:id","删除会议"],
["POST","/api/v1/meeting-notes/meetings/:id/shares","创建分享链接"],
["GET","/api/v1/meeting-notes/meetings/:id/shares","分享列表"],
["DELETE","/api/v1/meeting-notes/meetings/:id/shares/:shareId","撤销分享"],
["GET","/api/v1/meeting-notes/shared/:token","通过分享令牌查看会议"],
["POST","/api/v1/meeting-notes/shared/:token/import","通过分享链接导入会议"],
["POST","/api/v1/meeting-notes/ingest/parse","解析会议文件（本地解析器）"],
["POST","/api/v1/meeting-notes/meetings/:id/recompose-analysis","重做会议分析"],
["GET","/api/v1/meeting-notes/meetings/:id/grep","会议全文检索"],
["GET","/api/v1/meeting-notes/meetings/:id/axes","16 轴分析结果"],
["GET","/api/v1/meeting-notes/meetings/:id/speech-metrics","发言统计（时长/频次）"],
["GET","/api/v1/meeting-notes/meetings/:id/detail","会议详情聚合"],
["POST","/api/v1/meeting-notes/compute/axis","计算指定轴"],
["GET","/api/v1/meeting-notes/config/axis-recompute","轴重算配置"],
["GET","/api/v1/meeting-notes/scopes","Scope 列表"],
["GET","/api/v1/meeting-notes/scopes/:id","Scope 详情"],
["POST","/api/v1/meeting-notes/scopes","创建 Scope（项目/客户/话题）"],
["PUT","/api/v1/meeting-notes/scopes/:id","更新 Scope"],
["DELETE","/api/v1/meeting-notes/scopes/:id","删除 Scope"],
["POST","/api/v1/meeting-notes/scopes/:id/bindings","绑定会议到 Scope"],
["DELETE","/api/v1/meeting-notes/scopes/:id/bindings/:meetingId","解绑会议"],
["GET","/api/v1/meeting-notes/scopes/:id/meetings","Scope 下会议列表"],
["GET","/api/v1/meeting-notes/meetings/:id/scope-bindings","会议绑定的 Scope"],
["GET","/api/v1/meeting-notes/scopes/:id/role-trajectory","Scope 角色轨迹"],
["GET","/api/v1/meeting-notes/scopes/:id/people","Scope 关联人物"],
["GET","/api/v1/meeting-notes/people","人物列表"],
["POST","/api/v1/meeting-notes/people","创建人物"],
["GET","/api/v1/meeting-notes/people/:id/meetings","人物参会历史"],
["GET","/api/v1/meeting-notes/meetings/:id/participants-review","参会人审阅"],
["POST","/api/v1/meeting-notes/meetings/:id/participants/bind","绑定参会人"],
["GET","/api/v1/meeting-notes/people/:id","人物详情"],
["GET","/api/v1/meeting-notes/people/:id/commitments","人物承诺事项"],
["GET","/api/v1/meeting-notes/people/:id/speech-summary","人物发言摘要"],
["GET","/api/v1/meeting-notes/people/:id/blind-spots","人物盲点分析"],
["GET","/api/v1/meeting-notes/people/:id/llm-profile","人物 LLM 画像"],
["POST","/api/v1/meeting-notes/people/:id/llm-profile","生成人物 LLM 画像"],
["POST","/api/v1/meeting-notes/people/:id/import-as-expert","人物导入为专家库专家"],
["GET","/api/v1/meeting-notes/scopes/:id/responsibility","Scope 责任矩阵"],
["POST","/api/v1/meeting-notes/people/:id/merge","合并重复人物"],
["GET","/api/v1/meeting-notes/entity-merge-candidates","实体合并候选"],
["POST","/api/v1/meeting-notes/entity-merge-candidates/:id/approve","批准合并"],
["POST","/api/v1/meeting-notes/entity-merge-candidates/:id/reject","拒绝合并"],
["GET","/api/v1/meeting-notes/unresolved-mentions","未解析人物提及"],
["POST","/api/v1/meeting-notes/unresolved-mentions/:id/resolve","解析人物提及"],
["PUT","/api/v1/meeting-notes/people/:id","更新人物"],
["DELETE","/api/v1/meeting-notes/people/:id","删除人物"],
["GET","/api/v1/meeting-notes/scopes/:id/decisions","Scope 决策清单"],
["GET","/api/v1/meeting-notes/scopes/:id/assumptions","Scope 假设清单"],
["GET","/api/v1/meeting-notes/scopes/:id/open-questions","Scope 开放问题"],
["GET","/api/v1/meeting-notes/scopes/:id/risks","Scope 风险清单"],
["GET","/api/v1/meeting-notes/meetings/:id/necessity-audit","会议必要性审计"],
["GET","/api/v1/meeting-notes/meetings/:id/decision-quality","决策质量评估"],
["GET","/api/v1/meeting-notes/meetings/:id/silence","静默/参与度分析"],
["GET","/api/v1/meeting-notes/meetings/:id/biases","认知偏差检测"],
["GET","/api/v1/meeting-notes/meetings/:id/health","会议健康度"],
["GET","/api/v1/meeting-notes/meetings/:id/emotion-curve","情绪曲线"],
["GET","/api/v1/meeting-notes/meetings/:id/tensions","张力点分析"],
["GET","/api/v1/meeting-notes/meetings/:id/person-names","参会人姓名提取"],
["GET","/api/v1/meeting-notes/scopes/:id/judgments","Scope 判断记录"],
["GET","/api/v1/meeting-notes/scopes/:id/mental-models/hit-rate","心智模型命中率"],
["GET","/api/v1/meeting-notes/scopes/:id/consensus-tracks","共识演化轨迹"],
["GET","/api/v1/meeting-notes/scopes/:id/concept-drifts","概念漂移检测"],
["GET","/api/v1/meeting-notes/scopes/:id/topic-lineage","话题谱系"],
["GET","/api/v1/meeting-notes/scopes/:id/external-experts","外部专家关联"],
["GET","/api/v1/meeting-notes/scopes/:id/commitments","Scope 承诺汇总"],
["GET","/api/v1/meeting-notes/scopes/:id/provenance","Scope 出处溯源"],
["GET","/api/v1/meeting-notes/schedules","采集计划列表"],
["POST","/api/v1/meeting-notes/schedules","创建采集计划"],
["PUT","/api/v1/meeting-notes/schedules/:id","更新采集计划"],
["DELETE","/api/v1/meeting-notes/schedules/:id","删除采集计划"],
["POST","/api/v1/meeting-notes/runs","创建分析 Run"],
["GET","/api/v1/meeting-notes/runs","Run 列表"],
["GET","/api/v1/meeting-notes/runs/:id/stream","Run 进度（SSE）"],
["GET","/api/v1/meeting-notes/runs/_diagnostics","Run 诊断信息"],
["POST","/api/v1/meeting-notes/runs/_admin/reap-orphans","清理孤儿 Run"],
["POST","/api/v1/meeting-notes/runs/_admin/reload-routing-config","重载 Run 路由配置"],
["GET","/api/v1/meeting-notes/runs/:id","Run 详情"],
["POST","/api/v1/meeting-notes/runs/:id/cancel","取消 Run"],
["POST","/api/v1/meeting-notes/runs/:id/resume","恢复 Run"],
["GET","/api/v1/meeting-notes/runs/:id/salvage-oneshot-raw","抢救一次性原始输出"],
["POST","/api/v1/meeting-notes/versions","创建版本"],
["POST","/api/v1/meeting-notes/versions/:id/restore","恢复版本"],
["GET","/api/v1/meeting-notes/versions/:scopeKind/:axis","按 Scope/轴列版本"],
["GET","/api/v1/meeting-notes/versions/:id/diff","版本对比"],
["GET","/api/v1/meeting-notes/crosslinks","跨会议关联"],
["GET","/api/v1/meeting-notes/meetings/:id/cross-axis-clues","跨轴线索"],
["GET","/api/v1/meeting-notes/cross-axis-clues","跨轴线索总览"],
["POST","/api/v1/meeting-notes/crosslinks/recompute","重算跨会议关联"],
["GET","/api/v1/meeting-notes/scopes/:id/longitudinal/:kind","纵向分析（跨会议）"],
["POST","/api/v1/meeting-notes/longitudinal/recompute","重算纵向分析"],
]});

G({id:"g-mnsrc",title:"会议纪要采集渠道",prefix:"/api/v1/meeting-notes/sources",desc:"外部上传接入与采集源管理（挂在 meeting-notes 模块下）。上传任务默认自动触发 16 轴分析 run，完成后推送两段式 webhook：meeting_notes.uploaded → meeting_notes.analysis.completed。",eps:[
["GET","/api/v1/meeting-notes/sources","采集源列表（kind/active 过滤）"],
["POST","/api/v1/meeting-notes/sources","创建采集源（lark/zoom/teams/upload/folder/manual）"],
["PUT","/api/v1/meeting-notes/sources/:id","更新采集源（含 scheduleCron）"],
["DELETE","/api/v1/meeting-notes/sources/:id","删除采集源"],
["POST","/api/v1/meeting-notes/sources/import","触发采集（按 source）"],
["POST","/api/v1/meeting-notes/sources/:id/upload","单文件上传（兼容旧版，单回调）"],
["POST","/api/v1/meeting-notes/sources/upload-task","一键上传任务（推荐，两段式回调）"],
["GET","/api/v1/meeting-notes/sources/progress","运行中采集任务"],
["GET","/api/v1/meeting-notes/sources/history","采集历史"],
]});

G({id:"g-ceo",title:"CEO 决策驾驶舱",prefix:"/api/v1/ceo",desc:"双模主壳 + 6 房间 + Panorama + 外脑图书馆：面向决策者的跨模块聚合视图，支持按 Scope 预填与流式运行。",eps:[
["GET","/api/v1/ceo/health","模块健康检查"],
["GET","/api/v1/ceo/dashboard","驾驶舱总览面板"],
["GET","/api/v1/ceo/recommended-scopes","推荐关注 Scope"],
["GET","/api/v1/ceo/default-scopes","默认 Scope 配置"],
["POST","/api/v1/ceo/scopes/fill-all","全量预填 Scope 数据"],
["POST","/api/v1/ceo/runs/enqueue","入队决策分析 Run"],
["GET","/api/v1/ceo/runs/:runId/stream","Run 进度（SSE）"],
]});

G({id:"g-fav",title:"收藏",prefix:"/api/v1/favorites",desc:"报告/内容收藏管理。",eps:[
["GET","/api/v1/favorites/","收藏列表"],
["GET","/api/v1/favorites/check/:reportId","查询是否已收藏"],
["POST","/api/v1/favorites/","添加收藏"],
["DELETE","/api/v1/favorites/:reportId","取消收藏"],
["POST","/api/v1/favorites/batch-check","批量查询收藏状态"],
]});

G({id:"g-sent",title:"情感分析",prefix:"/api/v1/sentiment",desc:"v2.2 市场情绪指数（MSI）与舆情预警。",eps:[
["POST","/api/v1/sentiment/analyze","单条内容情感分析"],
["POST","/api/v1/sentiment/batch-analyze","批量情感分析"],
["GET","/api/v1/sentiment/topic/:topicId","话题情感分布"],
["GET","/api/v1/sentiment/msi","市场情绪指数（MSI）"],
["GET","/api/v1/sentiment/stats","情感统计"],
["GET","/api/v1/sentiment/alerts","情绪预警"],
["GET","/api/v1/sentiment/trend/:topicId","话题情绪趋势"],
]});

G({id:"g-v3",title:"公开 API v3",prefix:"/api/v3",desc:"对第三方开放的只读数据接口（热点/资讯/质量/情感/推荐），独立鉴权策略。",eps:[
["GET","/api/v3/health","公开 API 健康检查"],
["GET","/api/v3/rss/sources","RSS 源公开列表"],
["GET","/api/v3/rss/stats","RSS 统计"],
["GET","/api/v3/rss/items","RSS 条目"],
["GET","/api/v3/rss/items/:itemId","RSS 条目详情"],
["GET","/api/v3/rss/search","RSS 检索"],
["GET","/api/v3/hot-topics","热点话题"],
["GET","/api/v3/hot-topics/:topicId","话题详情"],
["GET","/api/v3/quality/score","内容质量评分"],
["POST","/api/v3/quality/batch","批量质量评分"],
["GET","/api/v3/sentiment/msi","市场情绪指数"],
["GET","/api/v3/sentiment/history","情绪历史"],
["POST","/api/v3/sentiment/analyze","情感分析"],
["GET","/api/v3/recommendations","推荐内容"],
["POST","/api/v3/recommendations/:itemId/feedback","推荐反馈"],
["POST","/api/v3/admin/rss/collect","触发 RSS 采集（需管理员）"],
["GET","/api/v3/admin/stats","管理统计"],
]});

G({id:"g-llm",title:"LLM 网关（Dashboard）",prefix:"/api/llm",desc:"LLM 提供商管理、模型配置与 OpenAI 兼容转发（供 Dashboard 等内部系统使用）。",eps:[
["GET","/api/llm/providers","可用 LLM 提供商列表"],
["POST","/api/llm/kimi-coding/chat","Kimi Coding 对话"],
["GET","/api/llm/model-config","读取模型配置"],
["PUT","/api/llm/model-config","更新模型配置"],
["POST","/api/llm/test-provider","测试提供商连通性"],
["POST","/api/llm/chat/completions","OpenAI 兼容对话接口"],
]});

G({id:"g-lg",title:"LangGraph 流水线",prefix:"/api/v1/langgraph",desc:"基于 LangGraph 的流水线任务（线程/状态/恢复/评审配置/流式输出）。",eps:[
["POST","/api/v1/langgraph/tasks","创建 LangGraph 任务"],
["POST","/api/v1/langgraph/tasks/:threadId/resume","恢复中断任务"],
["GET","/api/v1/langgraph/tasks/:threadId/state","任务状态"],
["GET","/api/v1/langgraph/tasks/:threadId/detail","任务详情"],
["GET","/api/v1/langgraph/tasks/:threadId/review-config","评审配置"],
["GET","/api/v1/langgraph/tasks/:threadId/annotations","任务标注"],
["GET","/api/v1/langgraph/tasks/:threadId/history","执行历史"],
["GET","/api/v1/langgraph/tasks/:threadId/stream","流式输出（SSE）"],
["GET","/api/v1/langgraph/graph","流水线图结构定义"],
]});

G({id:"g-ai",title:"AI 批量处理 (v6.1 RSS)",prefix:"/api/v1/ai",desc:"RSS 条目的 AI 批量分析与监测。注意：旧 rss_item_ai_analysis 链路已废弃，调度默认关闭。",eps:[
["POST","/api/v1/ai/batch-process","批量处理 RSS 条目"],
["GET","/api/v1/ai/rss-items/:id/ai-analysis","单条 AI 分析结果"],
["GET","/api/v1/ai/analysis-results","分析结果列表"],
["GET","/api/v1/ai/task-recommendations","任务推荐"],
["POST","/api/v1/ai/task-recommendations/:id/accept","接受推荐"],
["POST","/api/v1/ai/task-recommendations/:id/reject","拒绝推荐"],
["GET","/api/v1/ai/stats","统计概览"],
["GET","/api/v1/ai/stats/categories","分类统计"],
["GET","/api/v1/ai/stats/sentiments","情感统计"],
["POST","/api/v1/ai/feedback","提交反馈"],
["GET","/api/v1/ai/feedback/stats","反馈统计"],
["GET","/api/v1/ai/monitoring/metrics","监测指标"],
["GET","/api/v1/ai/monitoring/report","监测报告"],
["GET","/api/v1/ai/monitoring/alerts","监测告警"],
["POST","/api/v1/ai/monitoring/alerts/:id/acknowledge","确认告警"],
]});

G({id:"g-aias",title:"AI 批量处理 (v6.2 Assets)",prefix:"/api/v1/ai/assets",desc:"素材资产的 AI 分析：语义检索、相似/重复检测、深度分析。",eps:[
["GET","/api/v1/ai/assets/pending","待处理素材列表"],
["POST","/api/v1/ai/assets/batch-process","批量处理素材"],
["GET","/api/v1/ai/assets/assets/:id/ai-analysis","素材 AI 分析"],
["GET","/api/v1/ai/assets/assets/:id/deep-analysis","素材深度分析"],
["POST","/api/v1/ai/assets/semantic-search","语义检索"],
["GET","/api/v1/ai/assets/assets/:id/similar","相似素材"],
["GET","/api/v1/ai/assets/assets/:id/duplicates","重复素材检测"],
["GET","/api/v1/ai/assets/analysis-results","分析结果列表"],
["GET","/api/v1/ai/assets/task-recommendations","素材任务推荐"],
["GET","/api/v1/ai/assets/stats","统计概览"],
["GET","/api/v1/ai/assets/stats/themes","主题统计"],
["GET","/api/v1/ai/assets/stats/quality","质量统计"],
]});

G({id:"g-tax",title:"统一领域 Taxonomy",prefix:"/api/v1/taxonomy",desc:"跨模块统一领域分类体系（素材/内容库/专家库共用），启动时自动播种。",eps:[
["GET","/api/v1/taxonomy/domains","领域列表"],
["GET","/api/v1/taxonomy/domains/tree","领域树结构"],
["GET","/api/v1/taxonomy/domains/:code/usage","领域使用情况"],
["GET","/api/v1/taxonomy/resolve","领域解析（文本→领域）"],
["POST","/api/v1/taxonomy/domains","新增领域"],
["PATCH","/api/v1/taxonomy/domains/:code","更新领域"],
["POST","/api/v1/taxonomy/sync","手动触发领域同步"],
["GET","/api/v1/taxonomy/export","导出领域体系"],
["GET","/api/v1/taxonomy/audit","领域变更审计"],
]});
