// Phase H · wiki frontmatter parse / render + block extraction
//
// 功能:
// 1. parseFrontmatter(md): 读取 .md 文件头部 YAML，返回 { frontmatter, body }
// 2. renderFrontmatter(data): 把对象渲染为 --- ... --- 块（继承 templates.ts 风格）
// 3. extractBlocks(body, predicate): 从 body 中提取 <!-- block:xxx --> 包裹的段
// 4. replaceBlock(body, blockId, newContent): 替换或追加块
// 5. flattenTaxonomy(): 把 TAXONOMY 树展平成 84 条 [{code, name, parentCode, parentName}]
//    给 prompt + wikiGenerator 用
//
// frontmatter 形态参考 plan §A.2 三层结构（type/subtype + 身份层 + taxonomy 层 + ownership 层 + blocks）

import { TAXONOMY, type TaxonomySeed } from '../../../config/taxonomyData.js';

// ============================================================
// 类型
// ============================================================

export interface WikiFrontmatter {
  // 类型层
  type?: 'entity' | 'concept' | 'domain' | 'source' | 'index' | 'overview' | 'axis' | 'scope';
  subtype?: string;

  // 身份层
  canonical_name?: string;
  aliases?: string[];
  slug?: string;

  // taxonomy 层
  taxonomy_code?: string;
  taxonomy_codes_secondary?: string[];
  domains_legacy?: string[];

  // ownership 层
  app?: 'meeting-notes' | 'knowledge-library' | 'manual';
  generatedBy?: 'claude-cli' | 'API Oneshot' | 'wiki-generator' | 'manual-edit' | 'meeting-axes-generator' | 'meeting-scope-generator';
  firstCreatedBy?: string;
  firstCreatedAt?: string;
  lastEditedBy?: string;
  lastEditedAt?: string;

  // 块级 ownership
  blocks?: WikiBlockMeta[];

  // 旧 wikiGenerator 字段（兼容）
  entityType?: string;
  domain?: string;
  domains?: string[];
  factCount?: number;
  entityCount?: number;
  sources?: string[];
  meetingId?: string;
  date?: string;
  title?: string;
  participants?: string[];
  source?: string;
  assetId?: string;
  updatedAt?: string;
  autoGenerated?: boolean;

  // 透传未识别字段
  [key: string]: unknown;
}

export interface WikiBlockMeta {
  id: string;
  app: 'meeting-notes' | 'knowledge-library' | 'manual';
  via?: 'claude-cli' | 'API Oneshot' | 'wiki-generator' | 'manual-edit';
  meetingId?: string;
  addedAt: string;
}

export interface ParseResult {
  frontmatter: WikiFrontmatter;
  body: string;
}

// ============================================================
// parse / render YAML frontmatter
// ============================================================

const FRONT_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

export function parseFrontmatter(md: string): ParseResult {
  const m = md.match(FRONT_RE);
  if (!m) return { frontmatter: {}, body: md };

  const raw = m[1];
  const body = md.slice(m[0].length);
  const frontmatter = parseYaml(raw);
  return { frontmatter, body };
}

/** 微型 YAML parser — 只支持本模块写出的形态（标量 / 数组 / JSON-stringified 对象数组） */
function parseYaml(raw: string): WikiFrontmatter {
  const out: Record<string, unknown> = {};
  const lines = raw.split(/\r?\n/);
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim() || line.trimStart().startsWith('#')) { i += 1; continue; }
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$/);
    if (!m) { i += 1; continue; }
    const key = m[1];
    const rest = m[2];

    if (rest === '') {
      // 数组形态：连续 `  - item`
      const arr: unknown[] = [];
      i += 1;
      while (i < lines.length && /^\s+-\s+/.test(lines[i])) {
        arr.push(parseScalar(lines[i].replace(/^\s+-\s+/, '').trim()));
        i += 1;
      }
      out[key] = arr;
    } else {
      out[key] = parseScalar(rest);
      i += 1;
    }
  }
  return out as WikiFrontmatter;
}

function parseScalar(s: string): unknown {
  const t = s.trim();
  if (!t) return '';
  // 引号字符串
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1).replace(/\\"/g, '"').replace(/\\'/g, "'");
  }
  // 行内数组 [a, b]
  if (t.startsWith('[') && t.endsWith(']')) {
    const inner = t.slice(1, -1).trim();
    if (!inner) return [];
    return inner.split(',').map((x) => parseScalar(x.trim()));
  }
  // JSON 对象（内嵌的 JSON.stringify 出来的）
  if (t.startsWith('{') || t.startsWith('[')) {
    try { return JSON.parse(t); } catch { /* fall through */ }
  }
  // 数字 / 布尔
  if (t === 'true') return true;
  if (t === 'false') return false;
  if (t === 'null') return null;
  if (/^-?\d+$/.test(t)) return Number(t);
  if (/^-?\d+\.\d+$/.test(t)) return Number(t);
  return t;
}

export function renderFrontmatter(data: WikiFrontmatter): string {
  const lines: string[] = ['---'];
  for (const [k, v] of Object.entries(data)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      // 对象数组（如 blocks[]）用 JSON 行内格式，每条一行
      const isObjectArray = v.every((x) => x && typeof x === 'object' && !Array.isArray(x));
      if (isObjectArray) {
        lines.push(`${k}:`);
        for (const item of v) {
          lines.push(`  - ${escapeYaml(JSON.stringify(item))}`);
        }
      } else {
        lines.push(`${k}:`);
        for (const item of v) lines.push(`  - ${escapeYaml(String(item))}`);
      }
    } else if (typeof v === 'object') {
      lines.push(`${k}: ${escapeYaml(JSON.stringify(v))}`);
    } else {
      lines.push(`${k}: ${escapeYaml(String(v))}`);
    }
  }
  lines.push('---');
  return lines.join('\n');
}

function escapeYaml(s: string): string {
  if (/[:#\n"']/.test(s) || /^\s/.test(s) || /\s$/.test(s)) {
    return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return s;
}

// ============================================================
// block 提取 / 替换
// ============================================================

const BLOCK_RE_FACTORY = (id: string) =>
  new RegExp(`<!--\\s*block:${escapeRegex(id)}\\s*-->[\\s\\S]*?<!--\\s*\\/block:${escapeRegex(id)}\\s*-->`);

const ANY_BLOCK_RE = /<!--\s*block:([^\s>]+)\s*-->[\s\S]*?<!--\s*\/block:\1\s*-->/g;

export interface ExtractedBlock {
  id: string;
  raw: string;            // 含 <!-- block:xxx --> 包装的完整块
  content: string;        // 去掉包装的内容
}

export function extractBlocks(body: string): ExtractedBlock[] {
  const out: ExtractedBlock[] = [];
  for (const m of body.matchAll(ANY_BLOCK_RE)) {
    const id = m[1];
    const raw = m[0];
    const content = raw
      .replace(new RegExp(`<!--\\s*block:${escapeRegex(id)}\\s*-->\\s*\\n?`), '')
      .replace(new RegExp(`\\n?<!--\\s*\\/block:${escapeRegex(id)}\\s*-->`), '');
    out.push({ id, raw, content });
  }
  return out;
}

export function wrapBlock(id: string, content: string): string {
  return `<!-- block:${id} -->\n${content}\n<!-- /block:${id} -->`;
}

export function hasBlock(body: string, id: string): boolean {
  return BLOCK_RE_FACTORY(id).test(body);
}

/** 替换或追加（文末）一个 block；返回新 body */
export function upsertBlock(body: string, id: string, newContent: string): string {
  const wrapped = wrapBlock(id, newContent);
  if (hasBlock(body, id)) {
    return body.replace(BLOCK_RE_FACTORY(id), wrapped);
  }
  return `${body.trimEnd()}\n\n${wrapped}\n`;
}

/** 移除单个 block */
export function removeBlock(body: string, id: string): string {
  return body.replace(BLOCK_RE_FACTORY(id), '').replace(/\n{3,}/g, '\n\n');
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ============================================================
// taxonomy flatten + lookup
// ============================================================

export interface TaxonomyFlatNode {
  code: string;            // E07.LLM
  name: string;            // 大模型
  level: 1 | 2;
  parentCode?: string;     // E07
  parentName?: string;     // 人工智能
}

let _flatCache: TaxonomyFlatNode[] | null = null;

export function flattenTaxonomy(): TaxonomyFlatNode[] {
  if (_flatCache) return _flatCache;
  const out: TaxonomyFlatNode[] = [];
  for (const l1 of TAXONOMY) {
    out.push({ code: l1.code, name: l1.name, level: 1 });
    for (const child of l1.children ?? []) {
      out.push({
        code: child.code,
        name: child.name,
        level: 2,
        parentCode: l1.code,
        parentName: l1.name,
      });
    }
  }
  _flatCache = out;
  return out;
}

export function getTaxonomyNode(code: string): TaxonomyFlatNode | undefined {
  return flattenTaxonomy().find((n) => n.code === code);
}

export function isValidTaxonomyCode(code: string): boolean {
  return flattenTaxonomy().some((n) => n.code === code);
}

/** 给 prompt 用：列出所有 L2 code（不含 L1）以紧凑文本形式 */
export function renderTaxonomyForPrompt(): string {
  const lines: string[] = [];
  for (const l1 of TAXONOMY) {
    if (!l1.children || l1.children.length === 0) continue;
    const childList = l1.children.map((c) => `${c.code} ${c.name}`).join(' / ');
    lines.push(`  ${l1.code}-${l1.name}: ${childList}`);
  }
  // 加一个 E99.OTHER 兜底（如果不在 TAXONOMY 里）
  if (!isValidTaxonomyCode('E99.OTHER')) {
    lines.push('  E99-其他: E99.OTHER 其他');
  }
  return lines.join('\n');
}

/** 给定 free-text domain 字符串（如 "AI" / "金融科技"），尝试映射到 taxonomy_code */
export function mapFreeTextToTaxonomyCode(freeText: string): string | null {
  if (!freeText) return null;
  const norm = freeText.trim().toLowerCase();
  for (const node of flattenTaxonomy()) {
    if (node.name.toLowerCase() === norm) return node.code;
  }
  // 二分匹配（部分包含）
  for (const node of flattenTaxonomy()) {
    if (node.name.toLowerCase().includes(norm) || norm.includes(node.name.toLowerCase())) {
      return node.code;
    }
  }
  return null;
}
