#!/usr/bin/env tsx
// Stage 3: 文稿生成 - task_1774210080319
// 使用 SiliconFlow (DeepSeek-V3.2)

import { query } from '../src/db/connection.js';
import { getLLMRouter, initLLMRouter } from '../src/providers/index.js';

const TASK_ID = 'task_1774210080319';

async function main() {
  console.log('[Stage3] Starting Draft Generation...');
  
  initLLMRouter({ siliconFlowApiKey: process.env.SILICONFLOW_API_KEY });
  
  const task = (await query('SELECT * FROM tasks WHERE id = $1', [TASK_ID])).rows[0];
  console.log('[Stage3] Topic:', task.topic);
  console.log('[Stage3] Outline sections:', task.outline?.sections?.length || 0);
  console.log('[Stage3] Research insights:', task.research_data?.insights?.length || 0);

  const router = getLLMRouter();
  
  // 为每个大纲章节生成内容
  const sections = task.outline?.sections || [];
  const generatedSections: string[] = [];
  
  for (let i = 0; i < sections.length; i++) {
    const section = sections[i];
    console.log(`[Stage3] Generating section ${i + 1}/${sections.length}: ${section.title}`);
    
    const prompt = `
撰写研究报告章节："${section.title}"

主题：${task.topic}
章节描述：${section.content || '无'}

研究洞察：
${task.research_data?.insights?.map((ins: any) => `- ${ins.title}: ${ins.description}`).join('\n') || '暂无'}

要求：
- 字数：800-1200字
- 风格：专业研究报告
- 包含数据支撑

直接输出章节内容，不要包含标题。`;

    try {
      const result = await router.generate(prompt, 'writing', {
        temperature: 0.7,
        maxTokens: 2000,
      });
      
      generatedSections.push(`## ${section.title}\n\n${result.content.trim()}\n`);
      console.log(`[Stage3] Section ${i + 1} done (${result.content.length} chars)`);
    } catch (e: any) {
      console.error(`[Stage3] Section ${i + 1} failed:`, e.message);
      generatedSections.push(`## ${section.title}\n\n[内容生成中...]\n`);
    }
  }

  const fullDraft = generatedSections.join('\n---\n\n');
  
  // 保存 draft
  await query(
    `INSERT INTO draft_versions (id, task_id, version, content, change_summary, created_at)
     VALUES (gen_random_uuid(), $1, 1, $2, 'Generated by SiliconFlow DeepSeek-V3.2', NOW())`,
    [TASK_ID, fullDraft]
  );

  // 更新状态到 Stage 4
  await query(
    `UPDATE tasks SET status = 'reviewing', current_stage = 'blue_team_review', progress = 60 WHERE id = $1`,
    [TASK_ID]
  );

  console.log('[Stage3] ✅ Complete. Total length:', fullDraft.length);
}

main().catch(e => { console.error(e); process.exit(1); });
