// PrintableChat — 给 html2pdf 用的固定模板。
// 关键约束：
//   - 离屏渲染（容器是 absolute, top: -10000px），但 html2canvas 需要看见尺寸 → 用 fixed width
//   - 中文字体走系统：浏览器渲染时已经字体注入，html2canvas 截图直接拿到中文
//   - 避免 oklch / CSS variables（html2canvas 老版本对新 color space 支持差），全部用 hex
//   - role 之间硬色块区分；助手消息附带 reasoning（默认折叠展示，PDF 里直接展开）

import { forwardRef } from 'react';
import type { ChatMessage } from './types.js';
import type { ExportMeta } from './exportChat.js';
import './PrintableChat.css';

interface Props {
  messages: ChatMessage[];
  meta: ExportMeta;
}

function fmtTs(iso?: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString('zh-CN', {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  });
}

export const PrintableChat = forwardRef<HTMLDivElement, Props>(function PrintableChat(
  { messages, meta },
  ref,
) {
  const exportedAt = fmtTs(new Date().toISOString());
  const realMessages = messages.filter((m) => m.kind !== 'context');

  return (
    <div ref={ref} className="printable-chat">
      {/* ===== Header ===== */}
      <header className="printable-chat__header">
        <div className="printable-chat__title">会议追问</div>
        <div className="printable-chat__meeting">{meta.meetingTitle}</div>
        <div className="printable-chat__meta-row">
          <span className={`printable-chat__mode-badge printable-chat__mode-badge--${meta.mode}`}>
            {meta.mode === 'resume' ? 'Resume · Claude CLI' : 'Expert · Volcano DeepSeek R1'}
          </span>
          {meta.mode === 'resume' && meta.sessionId && (
            <span className="printable-chat__meta-item">
              session: <code>{meta.sessionId.slice(0, 6)}…{meta.sessionId.slice(-4)}</code>
            </span>
          )}
          {meta.mode === 'expert' && meta.expertName && (
            <span className="printable-chat__meta-item">专家: {meta.expertName}</span>
          )}
          {typeof meta.runCount === 'number' && (
            <span className="printable-chat__meta-item">运行 {meta.runCount} 轮</span>
          )}
          {meta.tension && (
            <span className="printable-chat__meta-item">
              张力 <strong>{meta.tension.id}</strong>「{meta.tension.topic}」
            </span>
          )}
        </div>
        <div className="printable-chat__meta-row printable-chat__meta-row--secondary">
          <span>会议 ID: <code>{meta.meetingId}</code></span>
          <span>导出于 {exportedAt}</span>
          <span>共 {realMessages.length} 条消息</span>
        </div>
      </header>

      {/* ===== Context block (if any) ===== */}
      {messages.find((m) => m.kind === 'context') && (
        <section className="printable-chat__context">
          <div className="printable-chat__context-label">📌 上下文</div>
          <div className="printable-chat__context-body">
            {messages.find((m) => m.kind === 'context')?.content}
          </div>
        </section>
      )}

      {/* ===== Messages ===== */}
      <main className="printable-chat__messages">
        {realMessages.map((m, i) => (
          <article
            key={i}
            className={`printable-chat__msg printable-chat__msg--${m.role}`}
          >
            <div className="printable-chat__msg-header">
              <span className="printable-chat__msg-role">
                {m.role === 'user' ? '🧑 用户' : m.role === 'assistant' ? '🤖 助手' : `⚙ ${m.role}`}
              </span>
              <span className="printable-chat__msg-ts">{fmtTs(m.timestamp)}</span>
            </div>
            {m.role === 'assistant' && m.reasoning && m.reasoning.trim() && (
              <div className="printable-chat__msg-reasoning">
                <div className="printable-chat__msg-reasoning-label">💭 思考过程</div>
                <div className="printable-chat__msg-reasoning-body">{m.reasoning}</div>
              </div>
            )}
            <div className="printable-chat__msg-content">{m.content || '（空）'}</div>
          </article>
        ))}
      </main>

      <footer className="printable-chat__footer">
        Generated by Pipeline · 会议工作台 — {exportedAt}
      </footer>
    </div>
  );
});
